# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  porter-build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Porter
      uses: deislabs/porter-gh-action@v0.1.1
    - name: Pull in jq mixin
      run: porter mixins install jq --url https://github.com/squillace/porter-jq/releases/download --version v0.1.0
    - uses: azure/docker-login@v1
      name: GHCR.IO Login
      with:
        login-server: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Porter Publish
      run: porter publish  
    
    - name: Retag bundle for Docker Hub
      run: |
        sed -i.bu 's/ghcr.io\/squillace\/gh-cnab\//squillace\//g' ./porter.yaml

    - uses: azure/docker-login@v1
      name: Docker Login
      with:
        login-server: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Porter Publish
      run: porter publish  

