# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  push_to_registries:
    name: Push to 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Setup Porter
        uses: deislabs/porter-gh-action@v0.1.1
      - name: Porter Publish
        run: porter publish  

      - uses: actions/checkout@v1
      - name: Retag bundle for Docker Hub
        run: |
          sed -i.bu 's/ghcr.io\/squillace\/gh-cnab\//squillace\//g' ./porter.yaml
          grep "tag" porter.yaml
        uses: docker/login-action@v1
        with:

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Porter Publish
        run: porter publish  





    


#        docker logout


