# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  porter-build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Porter
      uses: deislabs/porter-gh-action@v0.1.1
    - name: Pull in jq mixin
      run: porter mixins install jq --url https://github.com/squillace/porter-jq/releases/download --version v0.1.0
    - uses: azure/docker-login@v1
      name: GHCR.IO Login
      with:
        login-server: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PASSWORD }} #${{ github.token }} #
    - name: Porter Publish
      run: porter publish  
    
    - name: Retag bundle for Docker Hub
      run: |
        sed -i.bu 's/ghcr.io\/squillace\/gh-cnab\//squillace\//g' ./porter.yaml
        grep "tag" porter.yaml
        docker logout

    - uses: azure/docker-login@v1
      name: Docker Login
      with:
        login-server: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: checking dockerfile
      run: docker image ls
    - name: Porter Publish
      run: porter publish  
    - name: checking again
      run: docker image ls

